### PR TITLE
Now it is possible to use msgpack instead of JSON.

### PR DESCRIPTION
**Pull request by evgkul**
To do this call postRobot.enableMsgpack(window) from both sides. You need to check version of post-robot by yourself

### CODE REVIEW

**Comment by evgkul** [comment]
For unknown reasons npm didn't added msgpack5 in package.json...

**Comment by bluepnume** [comment]
Hi @evgkul -- thanks so much for the PR!

I'm wondering -- would it make sense to add generic support for serializers/deserializers? Then people could plug in whatever serializer they like, including msgpack.

Something like:

```
postRobot.registerSerializer({
    serialize(obj) {
        return msgpack5.encode(obj).toString('hex');
    },
    deserialize(str) {
        return msgpack5.decode(str);
    }
});
```

Then we avoid pulling in extra dependencies into the core post-robot bundle, and anyone would be able to plug-in their own favorite serializer.

**Comment by bluepnume** [comment]
By the way, congrats on the first PR! Happy to offer any help to get this ready to merge in. :)

**Comment by evgkul** [comment]
I think that with generic support of serializers/deserializers it will be too hard to synchronize them.

**Comment by bluepnume** [comment]
Can you elaborate? How would it be hard to synchronize them, and is that not a problem using msgpack also?

**Comment by evgkul** [comment]
Task of post-robot is to make communication between cross-domain iframes simpler. If host page will have serializer and iframe will not then they will communicate by JSON or simply will not work.

**Comment by bluepnume** [comment]
Makes total sense, but how do we avoid that problem even for this PR?

**Comment by evgkul** [comment]
For that is needed mechanism to send through JSON to other side a marker(unused property) and wait for response marker and then activate msgpack

**Comment by bluepnume** [comment]
Isn't that a problem with the current PR? If I sent a message but the other window has not done `enableMsgpack()` then it won't be able to correctly read the message, right?

**Comment by evgkul** [comment]
If it has support of msgpack it will be able to read
`if (typeof message === 'string') {
             parsedMessage = jsonParse(message);
         } else {
             parsedMessage = msgpack5.decode(message);
         }`

**Comment by bluepnume** [comment]
Ah -- I think that's going to be a problem. We need to support IE9, which I believe only supports string messages.

**Comment by evgkul** [comment]
When I will have some free time I will add base64 encoding if IE is detected

**Comment by bluepnume** [comment]
I'd prefer to go down the pluggable-serializer path. I just checked and the minified msgpack5 is still 120kb. That's 3 times the size of post-robot.min.js, and I don't feel like it makes sense to bundle it in, given that for most usecases JSON serialization is enough.

Totally get your concern about synchronizing the serializers. Perhaps we could do something like:

```
postRobot.registerSerializer('msgpack5', {
    serialize(obj) {
        return msgpack5.encode(obj).toString('hex');
    },
    deserialize(str) {
        return msgpack5.decode(str);
    }
});
```

Then pass `msgpack5` in each message, and error out if that deserializer has not been registered on the receiving end. That way people will be able to easily figure out in which pages they haven't added the serializer/deserializer.

Bear in mind -- postMessaging is just in-memory messaging, so the size of the message shouldn't be a bottleneck most of the time. But I do see value in being able to register custom serializer in case people want to pass across more elaborate data types.

**Comment by evgkul** [comment]
Hmm... I will try to add marker with array of serializers/deserializers

**Comment by evgkul** [comment]
... or will just replace msgpack 5 with https://github.com/kawanet/msgpack-lite (50kb) :)

**Comment by evgkul** [comment]
Well, for now I will close this pull request

**Comment by evgkul** [comment]
Moved this PR's commit into "msgpacksupport" branch

**Pull request closed without merging**
