### PR TITLE
Added config for same-origin communications

### PR DESCRIPTION
**Pull request by RaymondMik**
**Background**
In our team we used post-robot to build an API that handles communications between our Redux application and other applications which are located either in the same or another window object. In order to avoid having two different implementations for the same functionality, we decided to extend post-robot to optionally accept same-origin communications.

**Implementation**
I extended post-robot standard functionalities in order to optionally enable requests from the same window. I added the new property `ALLOW_SAME_ORIGIN` in the `CONFIG` object in _src/conf/config.js_ and a new condition check for `ALLOW_SAME_ORIGIN` to be false in _src/drivers/send/index.js_. All 24 tests run successfully.

**Usage**
`CONFIG.ALLOW_SAME_ORIGIN` is set to false by default. Set the config parameter to true before defining post-robot listeners and senders in order to enable same-origin communications.

```javascript
postRobot.CONFIG.ALLOW_SAME_ORIGIN = true

### CODE REVIEW

**Comment by bluepnume** [comment]
Looks good! But could you remove the /dist changes for now? These will be picked up automatically when I publish

**Comment by RaymondMik** [comment]
I reverted the changes in the /dist folder, please check it out.

**Comment by RaymondMik** [comment]
I could not find the reason why file permission was changed from 644 to 755. I have manually set file permission of the files in the ./dist folder back to 644. Please check it out.

**Comment by bluepnume** [comment]
Looks good! merging

**Pull request merged**
