### PR TITLE
Fix for ignoring timeout

### PR DESCRIPTION
**Pull request by mrVictorios**
Hello,

in a use case wich requires to set the timeout, post-robot still ignore the value. This fix the issue. Reason for the issue the "timeout" option was not passed to the send method.

*fix style

### CODE REVIEW

**Comment by bluepnume** [comment]
Can you please:

- Add a new config value for this, called `CONFIG.CHILD_WINDOW_TIMEOUT`. I don't want to overload `BRIDGE_TIMEOUT`.
- Please only make changes to `src/` and remove any refactoring, style changes, or changes to `/dist`. Once your change is merged I'll build and publish.

**Comment by mrVictorios** [comment]
I made the adjustments.

**Comment by bluepnume** [comment]
> - Please only make changes to `src/` and remove any refactoring, style changes, or changes to `/dist`. Once your change is merged I'll build and publish.

^ I'm still seeing this, along with a lot of console logs. Can you please just add the two lines that are necessary for this change in src/ -- the change to config.js, and the change to ready.js to set the default window load timeout.

**Comment by mrVictorios** [comment]
I created a new branch from my master and reset it to the commit f7daefd and add my changes.

**Comment by bluepnume** [comment]
Doesn't seem to have worked -- https://github.com/krakenjs/post-robot/pull/46/files still shows a lot of changes that aren't needed for this PR. Did you push your changes to your fork?

**Comment by mrVictorios** [comment]
Ok I close this Pull Request Create a new Fork with changes, that should be passed :)

**Pull request closed without merging**
